language: go
go:
  - 1.11.x
service:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
jobs:
  include:
    - stage: test
      script: go test ./...
    - stage: build
      script: go build .
